"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/authContext";
import { AppSidebar } from "@/components/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ThemeProvidersContext } from "@/provider/theme-provider";
import { Header } from "@/components/header";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Remove the `export` keyword here
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Define routes where the sidebar and header should be hidden
  const hideSidebarAndHeader = ["/signup", "/login"].includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <ThemeProvidersContext>
            <SidebarProvider>
              {hideSidebarAndHeader ? (
                <main className="w-full h-screen">{children}</main>
              ) : (
                <div className="flex w-full h-screen bg-gradient-to-br">
                  <AppSidebar />
                  <main className="flex-1 overflow-y-auto w-full">
                    <Header />
                    {children}
                  </main>
                </div>
              )}
            </SidebarProvider>
          </ThemeProvidersContext>
        </AuthProvider>
      </body>
    </html>
  );
}